<?php

namespace Database\Seeders;

use App\Models\AccountHead;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AccountHeadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10',
                'name' => 'Asset',
                'level' => 1,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010',
                'name' => 'Non-current Asset',
                'level' => 2,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '101001',
                'name' => 'Tangible Fixed Assets At Cost-Owned',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010010001',
                'name' => 'Land and Buliding',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100010001',
                'name' => 'Land ',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100010002',
                'name' => 'Building ',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100010003',
                'name' => 'Accumulated Depreceiation - Building ',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010010002',
                'name' => 'Plant & Machinery',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100020001',
                'name' => 'Plant & Machinery',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100020002',
                'name' => 'Accumulated Depreceiation - Plant & Machinery',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100020003',
                'name' => 'Containers',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100020004',
                'name' => 'Accumulated Depreceiation - Containers ',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010010003',
                'name' => 'Office Equipments',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100030001',
                'name' => 'Office Equipments',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100030002',
                'name' => 'Accumulated Depreceiation - Office Equipment',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100030003',
                'name' => 'Generators',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100030004',
                'name' => 'Accumulated Depreceiation - Generators',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100030005',
                'name' => 'Office Furniture & Fixtures',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100030006',
                'name' => 'Accumulated Depreceiation - Office Furniture & Fixtures',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100030007',
                'name' => 'Office IT Equipments',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100030008',
                'name' => 'Accumulated Depreceiation - It Equipments',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],


            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010010004',
                'name' => 'Site Equipments ',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100040001',
                'name' => 'Site Equipments ',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100040002',
                'name' => 'Accumulated Depreceiation - Site Equipment',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100040003',
                'name' => 'Site Furniture & Fixtures',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100040004',
                'name' => 'Accumulated Depreceiation - Site Furniture & Fixtures',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100040005',
                'name' => 'Site IT Equipments',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100040006',
                'name' => 'Accumulated Depreceiation -  Site IT Equipments',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],


            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010010005',
                'name' => 'Motor Vehicles',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100050001',
                'name' => 'Motor Vehicles',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100050002',
                'name' => 'Accumulated Depreceiation - Vehicles',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010010006',
                'name' => 'Electrical Equipments',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100060001',
                'name' => 'Electrical Equipments',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100060002',
                'name' => 'Accumulated Depreceiation - Electrical Equipments',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010010007',
                'name' => 'Others',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100070001',
                'name' => 'Others',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100100070002',
                'name' => 'Accumulated Depreceiation - Others',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],



            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '101002',
                'name' => 'Intangible Assets Assets At Cost-Owned',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010020001',
                'name' => 'Software',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100200010001',
                'name' => 'Software',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100200010002',
                'name' => 'Accumulated Amortization - Software',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],


            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '101003',
                'name' => 'Long Term Deposits / Guarantees',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010030001',
                'name' => 'Deposits Paid to Mumtaz City',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100300010001',
                'name' => 'Mumtaz City - Meter Charges',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '101004',
                'name' => 'Long Term Loans',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '101005',
                'name' => 'Long Term Prepayments',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '101006',
                'name' => 'Long Term Advances',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '101007',
                'name' => 'Long Term Other Receviables',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '101008',
                'name' => 'Defeered Tax Asset',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010080001',
                'name' => 'Income Tax',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100800010001',
                'name' => 'Income Tax Refundable/ Payable',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1010080002',
                'name' => 'Sales Tax',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10100800020001',
                'name' => 'Sales Tax Payable/ Refundable',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '101009',
                'name' => 'Other Assets',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],


            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020',
                'name' => 'Current Asset',
                'level' => 2,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            // [
            //     'site_id' => 1,
            //     'modelable_id' => 1,
            //     'modelable_type' => 'App\Models\Unit',
            //     'code' => '1020200001',
            //     'name' => 'GF-01 Receivable',
            //     'level' => 4,
            //     'account_type' => 'debit',
            //     'opening_balance' => null,
            //     'status' => true,
            //     'closing_balance' => null,
            //     'opening_balance_date' => null,
            //     'closing_balance_date' => null,
            //     'show_in_vouchers'=> true,
            // ],
            // [
            //     'site_id' => 1,
            //     'modelable_id' => 2,
            //     'modelable_type' => 'App\Models\Unit',
            //     'code' => '1020200002',
            //     'name' => 'GF-02 Receivable',
            //     'level' => 4,
            //     'account_type' => 'debit',
            //     'opening_balance' => null,
            //     'status' => true,
            //     'closing_balance' => null,
            //     'opening_balance_date' => null,
            //     'closing_balance_date' => null,
            //     'show_in_vouchers'=> true,
            // ],
            // [
            //     'site_id' => 1,
            //     'modelable_id' => 3,
            //     'modelable_type' => 'App\Models\Unit',
            //     'code' => '1020200003',
            //     'name' => 'GF-03 Receivable',
            //     'level' => 4,
            //     'account_type' => 'debit',
            //     'opening_balance' => null,
            //     'status' => true,
            //     'closing_balance' => null,
            //     'opening_balance_date' => null,
            //     'closing_balance_date' => null,
            //     'show_in_vouchers'=> true,
            // ],
            // [
            //     'site_id' => 1,
            //     'modelable_id' => 4,
            //     'modelable_type' => 'App\Models\Unit',
            //     'code' => '1020200004',
            //     'name' => 'GF-04 Receivable',
            //     'level' => 4,
            //     'account_type' => 'debit',
            //     'opening_balance' => null,
            //     'status' => true,
            //     'closing_balance' => null,
            //     'opening_balance_date' => null,
            //     'closing_balance_date' => null,
            //     'show_in_vouchers'=> true,
            // ],

            // [
            //     'site_id' => 1,
            //     'modelable_id' => 5,
            //     'modelable_type' => 'App\Models\Unit',
            //     'code' => '1020200005',
            //     'name' => 'GF-05 Receivable',
            //     'level' => 4,
            //     'account_type' => 'debit',
            //     'opening_balance' => null,
            //     'status' => true,
            //     'closing_balance' => null,
            //     'opening_balance_date' => null,
            //     'closing_balance_date' => null,
            //     'show_in_vouchers'=> true,
            // ],
            // [
            //     'site_id' => 1,
            //     'modelable_id' => null,
            //     'modelable_type' => null,
            //     'code' => '1020210001',
            //     'name' => '3F-01 Receivable',
            //     'level' => 4,
            //     'account_type' => 'debit',
            //     'opening_balance' => null,
            //     'status' => true,
            //     'closing_balance' => null,
            //     'opening_balance_date' => null,
            //     'closing_balance_date' => null,
            //     'show_in_vouchers'=> true,
            // ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '102001',
                'name' => 'Raw Material, Store and Spares',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020010001',
                'name' => 'Raw Material',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020010002',
                'name' => 'Store and Spares',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '102010',
                'name' => 'Other Receivables',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020100001',
                'name' => 'Receivable From Associated Parties',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10201000010001',
                'name' => 'Receivable From Directors',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10201000010002',
                'name' => 'Receivable From J7 Global Apartments',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020100002',
                'name' => 'Other Receivables',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '102030',
                'name' => 'Advances',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020300001',
                'name' => 'Advances',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020300002',
                'name' => 'Advance To Contractors',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10203000020001',
                'name' => 'Advance To Karachi Steel',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10203000020002',
                'name' => 'Advance To Sraffolding/Joints',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020300003',
                'name' => 'Advance To Sub Contractors',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020300004',
                'name' => 'Advance To Suppliers',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020300005',
                'name' => 'Advance Income Tax',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10203000050001',
                'name' => 'Advance Tax On Land',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020300006',
                'name' => 'Other Advances',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '102071',
                'name' => 'Prepayments',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '102072',
                'name' => 'Short Term Deposits/Guarantees',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '102073',
                'name' => 'Short Term Loans',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020730001',
                'name' => 'Short Term Loans',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10207300010001',
                'name' => 'Short Term Loans - Ceo',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10207300010002',
                'name' => 'Short Term Loans - Taj Sb',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '102074',
                'name' => 'Investments / Adjustments',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020740001',
                'name' => 'Property',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020740002',
                'name' => 'Vehicles',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020740003',
                'name' => 'Others',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '102090',
                'name' => 'Cash, Bank, Clearing Account',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020901000',
                'name' => 'Bank',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10209010001001',
                'name' => 'MCB Bank',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10209010001002',
                'name' => 'Meezan Bank - 6560',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10209010001003',
                'name' => 'Meezan Bank - 1650',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10209010001010',
                'name' => 'Cheques Clearing Account',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],


            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '1020902000',
                'name' => 'Cash',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10209020001001',
                'name' => 'Cash at Office',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '10209020001002',
                'name' => 'Petty Cash',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '20',
                'name' => 'Liability',
                'level' => 1,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '2010',
                'name' => 'Non-current liability',
                'level' => 2,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '2020',
                'name' => 'Current liability',
                'level' => 2,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '202010',
                'name' => 'Account Payable',
                'level' => 3,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],


            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '2020101000',
                'name' => 'Customer AP',
                'level' => 4,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],


            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '2020102000',
                'name' => 'Dealer AP',
                'level' => 4,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],


            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '2020103000',
                'name' => 'Supplier AP',
                'level' => 4,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '30',
                'name' => 'Equity',
                'level' => 1,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '3010',
                'name' => 'Ordinary Shares',
                'level' => 2,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '301010',
                'name' => 'Ordinary Shares',
                'level' => 3,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '3010101000',
                'name' => 'Ordinary Shares',
                'level' => 4,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '30101010001001',
                'name' => 'Ordinary Shares - Person',
                'level' => 5,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '40',
                'name' => 'Revenue',
                'level' => 1,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '4010',
                'name' => 'Revenue',
                'level' => 2,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '401010',
                'name' => 'Revenue',
                'level' => 3,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '4010101000',
                'name' => 'Revenue',
                'level' => 4,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '40101010001001',
                'name' => 'Revenue - Sales',
                'level' => 5,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '40101010001002',
                'name' => 'Revenue - Cancellation Charges',
                'level' => 5,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '40101010001003',
                'name' => 'Revenue - Transfer Fees',
                'level' => 5,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '40101010001004',
                'name' => 'Revenue - Other Income',
                'level' => 5,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],


            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '4020',
                'name' => 'Revenue Reversals',
                'level' => 2,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '402010',
                'name' => 'Revenue Reversals',
                'level' => 3,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '4020101000',
                'name' => 'Revenue Reversals',
                'level' => 4,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '40201010001001',
                'name' => 'Buyback Account',
                'level' => 5,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '40201010001002',
                'name' => 'Refund Account',
                'level' => 5,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '40201010001003',
                'name' => 'Cancellation Account',
                'level' => 5,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '40201010001004',
                'name' => 'Sales Plan Disapproval Account',
                'level' => 5,
                'account_type' => 'credit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '50',
                'name' => 'Cost of Goods - Expenses',
                'level' => 1,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '5010',
                'name' => 'Cost of Goods Sold',
                'level' => 2,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '60',
                'name' => 'Sales, General Admin - Expense',
                'level' => 1,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '6010',
                'name' => 'General Admin Expenses',
                'level' => 2,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '6030',
                'name' => 'Sales and Marketing Expense',
                'level' => 2,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '601001',
                'name' => 'Discount Allowed',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '603010',
                'name' => 'Dealer Rebate and Incentive',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '6010011000',
                'name' => 'Cash Discount',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '6030101000',
                'name' => 'Dealer Rebate and Incentive',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '60100110001001',
                'name' => 'Cash Discount',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '60301010001001',
                'name' => 'Dealer Rebate Expense',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '60301010002001',
                'name' => 'Dealer Incentive Expense',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '603020',
                'name' => 'Profit Paid',
                'level' => 3,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '6030201000',
                'name' => 'Profit Paid',
                'level' => 4,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],
            [
                'site_id' => 1,
                'modelable_id' => null,
                'modelable_type' => null,
                'code' => '60302010001001',
                'name' => 'Customer Own Paid Expense',
                'level' => 5,
                'account_type' => 'debit',
                'opening_balance' => null,
                'status' => true,
                'closing_balance' => null,
                'opening_balance_date' => null,
                'closing_balance_date' => null,
                'show_in_vouchers'=> true,
            ],

        ];

        foreach ($data as $item) {
            (new AccountHead())->create($item);
        }
    }
}
