<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\{Role, Permission};

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        (new Permission())->insert([

            // Roles Routes
            [
                'name' => 'roles.index',
                'guard_name' => 'web',
                'show_name' => 'View Roles',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.create',
                'guard_name' => 'web',
                'show_name' => 'Create Role',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.store',
                'guard_name' => 'web',
                'show_name' => 'Store Role',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.edit',
                'guard_name' => 'web',
                'show_name' => 'Edit Role',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.update',
                'guard_name' => 'web',
                'show_name' => 'Update Role',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.destroy',
                'show_name' => 'Destroy Role',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.destroy-selected',
                'guard_name' => 'web',
                'show_name' => 'Destroy Selected Roles',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.make-default',
                'guard_name' => 'web',
                'show_name' => 'Make Default Roles',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Permissions Routes
            [
                'name' => 'permissions.index',
                'guard_name' => 'web',
                'show_name' => 'View Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.view_all',
                'guard_name' => 'web',
                'show_name' => 'View All Site Roles Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.create',
                'guard_name' => 'web',
                'show_name' => 'Create Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.store',
                'guard_name' => 'web',
                'show_name' => 'Store Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.edit',
                'guard_name' => 'web',
                'show_name' => 'Edit Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.update',
                'guard_name' => 'web',
                'show_name' => 'Update Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.destroy',
                'guard_name' => 'web',
                'show_name' => 'Destroy Permission',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.destroy-selected',
                'guard_name' => 'web',
                'show_name' => 'Destroy Selected Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.assign-permission',
                'show_name' => 'Assign Permission',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.revoke-permission',
                'show_name' => 'Revoke Permission',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.edit-own-permission',
                'show_name' => 'Edit Own Permission',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'countries.cities',
                'show_name' => 'View Cities',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sites Routes
            [
                'name' => 'site.cache.flush',
                'guard_name' => 'web',
                'show_name' => 'Refresh Site Cache',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.index',
                'show_name' => 'View Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.create',
                'show_name' => 'Create Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.store',
                'show_name' => 'Store Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.edit',
                'show_name' => 'Edit Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.update',
                'show_name' => 'Update Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.destroy',
                'show_name' => 'Destroy Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.destroy-selected',
                'show_name' => 'Destroy Selected Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.configurations.configView',
                'show_name' => 'View Sites Configuration',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.configurations.configStore',
                'show_name' => 'Store Sites Configuration',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Types Routes
            [
                'name' => 'sites.types.index',
                'show_name' => 'View Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.create',
                'show_name' => 'Create Site Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.store',
                'show_name' => 'Store Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.edit',
                'show_name' => 'Edit Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.update',
                'show_name' => 'Update Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.destroy',
                'show_name' => 'Destroy Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.destroy-selected',
                'show_name' => 'Destroy Selected Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Additional Costs Routes
            [
                'name' => 'sites.additional-costs.index',
                'show_name' => 'View Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.create',
                'show_name' => 'Create Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.store',
                'show_name' => 'Store Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.edit',
                'show_name' => 'Edit Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.update',
                'show_name' => 'Update Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.destroy-selected',
                'show_name' => 'Destroy Selected Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Floor Routes
            [
                'name' => 'sites.floors.index',
                'show_name' => 'View Sites Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.create',
                'show_name' => 'Create Sites Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.store',
                'show_name' => 'Store Sites Floor',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.edit',
                'show_name' => 'Edit Sites Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.update',
                'show_name' => 'Update Sites Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.destroy-selected',
                'show_name' => 'Destroy Selected Sites Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.copyView',
                'show_name' => 'View Sites Copy Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.copyStore',
                'show_name' => 'Store Copy Sites Floor ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.pending.get',
                'show_name' => 'Get Pending floors ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.preview',
                'show_name' => ' Preview floors ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.changes.save',
                'show_name' => 'Save Preview floors ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // Unit Routes
            [
                'name' => 'sites.floors.units.index',
                'show_name' => 'View Sites Floors Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.create',
                'show_name' => 'Create Site Floor Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.store',
                'show_name' => 'Store Site Floor Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.edit',
                'show_name' => 'Edit Site Floor Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.update',
                'show_name' => 'Update Sites Floor Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.destroy-selected',
                'show_name' => 'Destroy Sites Floors Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.preview',
                'show_name' => 'Preview Unit ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.changes.save',
                'show_name' => ' Save Preview Unit ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Batchs Routes
            [
                'name' => 'batches.byid',
                'show_name' => 'Batches By id',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sales Plan
            [
                'name' => 'sites.floors.units.sales-plans.index',
                'show_name' => 'View Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.create',
                'show_name' => 'Create Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.store',
                'show_name' => 'Store Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.edit',
                'show_name' => 'Edit Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.update',
                'show_name' => 'Update Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.destroy-selected',
                'show_name' => 'Destroy Selected Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.approve-sales-plan',
                'show_name' => 'Approve Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.disapprove-sales-plan',
                'show_name' => 'Disapprove Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //Sales Plan Print
            [
                'name' => 'sites.floors.units.sales-plans.templates.print',
                'show_name' => 'Print Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Stakeholders
            [
                'name' => 'sites.stakeholders.index',
                'show_name' => 'View Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.create',
                'show_name' => 'Create Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.store',
                'show_name' => 'Store Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.edit',
                'show_name' => 'Edit Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.update',
                'show_name' => 'Update Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.destroy',
                'show_name' => 'Destroy Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.destroy-selected',
                'show_name' => 'Destroy Selected Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Lead Sources Routes
            [
                'name' => 'sites.lead-sources.index',
                'show_name' => 'View Lead Sources',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.lead-sources.create',
                'show_name' => 'Create Lead Source',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.lead-sources.store',
                'show_name' => 'Store Lead Source',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.lead-sources.edit',
                'show_name' => 'Edit Lead Source',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.lead-sources.update',
                'show_name' => 'Update Lead Source',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.lead-sources.destroy-selected',
                'show_name' => 'Delete Selected Lead Sources',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // sales Plan Receipts
            [
                'name' => 'sites.receipts.index',
                'show_name' => 'View Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.create',
                'show_name' => 'Create Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.store',
                'show_name' => 'Store Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.show',
                'show_name' => 'View Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'name' => 'sites.receipts.edit',
            //     'show_name' => 'View Receipt Details',
            //     'guard_name' => 'web',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'sites.receipts.update',
            //     'show_name' => 'Update Receipts',
            //     'guard_name' => 'web',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'sites.receipts.destroy-selected',
            //     'show_name' => 'Destroy Selected Receipts',
            //     'guard_name' => 'web',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            [
                'name' => 'sites.receipts.make-active-selected',
                'show_name' => 'Make Active Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.destroy-draft',
                'show_name' => 'Destroy Draft Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.templates.print',
                'show_name' => 'Print Selected Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Customer File Management Routes
            [
                'name' => 'sites.file-managements.customers',
                'show_name' => 'File Management Customers',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units',
                'show_name' => 'File Management Customers Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.index',
                'show_name' => 'Create Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.create',
                'show_name' => 'Create Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.store',
                'show_name' => 'Store Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.edit',
                'show_name' => 'Edit Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.update',
                'show_name' => 'Update Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.destroy-selected',
                'show_name' => 'Delete Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // file management rebate incentive
            [
                'name' => 'sites.file-managements.rebate-incentive.index',
                'show_name' => 'View Rebate Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.rebate-incentive.create',
                'show_name' => 'Create Rebate Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.rebate-incentive.store',
                'show_name' => 'Store Rebate Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.rebate-incentive.edit',
                'show_name' => 'Edit Rebate Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.rebate-incentive.update',
                'show_name' => 'Update Rebate Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.view-files',
                'show_name' => 'View Customer Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // file management dealer incentive
            [
                'name' => 'sites.file-managements.dealer-incentive.index',
                'show_name' => 'View Dealer Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.dealer-incentive.create',
                'show_name' => 'Create Dealer Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.dealer-incentive.store',
                'show_name' => 'Store Dealer Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File Refund
            [
                'name' => 'sites.file-managements.file-refund.index',
                'show_name' => 'View File Refund',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-refund.create',
                'show_name' => 'View File Refund',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-refund.store',
                'show_name' => 'View File Refund',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-refund.approve',
                'show_name' => 'Approve File Refund Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-refund.preview',
                'show_name' => 'Preview File Refund',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File Buy Back
            [
                'name' => 'sites.file-managements.file-buy-back.index',
                'show_name' => 'View File Buy Back',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-buy-back.create',
                'show_name' => 'View File Buy Back',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-buy-back.store',
                'show_name' => 'View File Buy Back',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-buy-back.approve',
                'show_name' => 'Approve File Buy Back Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-buy-back.preview',
                'show_name' => 'Preview File Buy Back',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File Cancellation
            [
                'name' => 'sites.file-managements.file-cancellation.index',
                'show_name' => 'View File Cancellation',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-cancellation.create',
                'show_name' => 'View File Cancellation',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-cancellation.store',
                'show_name' => 'View File Cancellation',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-cancellation.approve',
                'show_name' => 'Approve File Cancallation Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File resale
            [
                'name' => 'sites.file-managements.file-resale.index',
                'show_name' => 'View File Re-sale',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-resale.create',
                'show_name' => 'View File Re-sale',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-resale.store',
                'show_name' => 'View File Re-sale',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-resale.approve',
                'show_name' => 'Approve File Resale Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File title transfer
            [
                'name' => 'sites.file-managements.file-title-transfer.index',
                'show_name' => 'View File Title-Transfer',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-title-transfer.create',
                'show_name' => 'View File Title-Transfer',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-title-transfer.store',
                'show_name' => 'View File Title-Transfer',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-title-transfer.approve',
                'show_name' => 'Approve File Title Transfer Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File title adjustment
            [
                'name' => 'sites.file-managements.file-adjustment.index',
                'show_name' => 'View File Adjustment',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-adjustment.create',
                'show_name' => 'View File Adjustment',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-adjustment.store',
                'show_name' => 'View File Adjustment',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-adjustment.approve',
                'show_name' => 'Approve File Title Adjustment Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File unit shifting
            [
                'name' => 'sites.file-managements.unit-shifting.index',
                'show_name' => 'View File Unit Shifting',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.unit-shifting.create',
                'show_name' => 'View File Unit Shifting',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.unit-shifting.store',
                'show_name' => 'View File Unit Shifting',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Commands Route
            [
                'name' => 'commands.command',
                'show_name' => 'Commands Permissions',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Users
            [
                'name' => 'sites.users.index',
                'show_name' => 'View Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.create',
                'show_name' => 'Create Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.store',
                'show_name' => 'Store Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.edit',
                'show_name' => 'Edit Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.update',
                'show_name' => 'Update Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.destroy',
                'show_name' => 'Destroy Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.destroy-selected',
                'show_name' => 'Destroy Selected Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.edit.password',
                'show_name' => 'Edit Sites Users Password',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // Users Teams
            [
                'name' => 'sites.teams.index',
                'show_name' => 'View Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.create',
                'show_name' => 'Create Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.store',
                'show_name' => 'Store Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.edit',
                'show_name' => 'Edit Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.update',
                'show_name' => 'Update Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.destroy',
                'show_name' => 'Destroy Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.destroy-selected',
                'show_name' => 'Destroy Selected Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        (new Role())->find(1)->givePermissionTo((new Permission())->pluck('id'));
    }
}
