<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\{Role, Permission};

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        (new Permission())->insert([

            // Roles Routes
            [
                'name' => 'roles.index',
                'guard_name' => 'web',
                'show_name' => 'Can View Roles',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.create',
                'guard_name' => 'web',
                'show_name' => 'Can Create Role',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.store',
                'guard_name' => 'web',
                'show_name' => 'Can Store Role',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.edit',
                'guard_name' => 'web',
                'show_name' => 'Can Edit Role',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.update',
                'guard_name' => 'web',
                'show_name' => 'Can Update Role',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.destroy',
                'show_name' => 'Can Destroy Role',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.destroy-selected',
                'guard_name' => 'web',
                'show_name' => 'Can Destroy Selected Roles',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'roles.make-default',
                'guard_name' => 'web',
                'show_name' => 'Can Make Default Roles',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Permissions Routes
            [
                'name' => 'permissions.index',
                'guard_name' => 'web',
                'show_name' => 'Can View Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.view_all',
                'guard_name' => 'web',
                'show_name' => 'Can View All Site Roles Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.create',
                'guard_name' => 'web',
                'show_name' => 'Can Create Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.store',
                'guard_name' => 'web',
                'show_name' => 'Can Store Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.edit',
                'guard_name' => 'web',
                'show_name' => 'Can Edit Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.update',
                'guard_name' => 'web',
                'show_name' => 'Can Update Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.destroy',
                'guard_name' => 'web',
                'show_name' => 'Can Destroy Permission',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.destroy-selected',
                'guard_name' => 'web',
                'show_name' => 'Can Destroy Selected Permissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.assign-permission',
                'show_name' => 'Can Assign Permission',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.revoke-permission',
                'show_name' => 'Can Revoke Permission',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'permissions.edit-own-permission',
                'show_name' => 'Can Edit Own Permission',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'countries.cities',
                'show_name' => 'Can View Cities',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sites Routes
            [
                'name' => 'site.cache.flush',
                'guard_name' => 'web',
                'show_name' => 'Can Refresh Site Cache',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.index',
                'show_name' => 'Can View Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.create',
                'show_name' => 'Can Create Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.store',
                'show_name' => 'Can Store Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.edit',
                'show_name' => 'Can Edit Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.update',
                'show_name' => 'Can Update Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.destroy',
                'show_name' => 'Can Destroy Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.destroy-selected',
                'show_name' => 'Can Destroy Selected Sites',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.configurations.configView',
                'show_name' => 'Can View Sites Configuration',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.configurations.configStore',
                'show_name' => 'Can Store Sites Configuration',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Types Routes
            [
                'name' => 'sites.types.index',
                'show_name' => 'Can View Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.create',
                'show_name' => 'Can Create Site Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.store',
                'show_name' => 'Can Store Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.edit',
                'show_name' => 'Can Edit Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.update',
                'show_name' => 'Can Update Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.destroy',
                'show_name' => 'Can Destroy Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.destroy-selected',
                'show_name' => 'Can Destroy Selected Sites Types',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.importTypes',
                'show_name' => 'Can Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.importTypesPreview',
                'show_name' => 'Can View Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.storePreview',
                'show_name' => 'Can View store Preview',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.types.saveImport',
                'show_name' => 'Can Save Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Additional Costs Routes
            [
                'name' => 'sites.additional-costs.index',
                'show_name' => 'Can View Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.create',
                'show_name' => 'Can Create Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.store',
                'show_name' => 'Can Store Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.edit',
                'show_name' => 'Can Edit Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.update',
                'show_name' => 'Can Update Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.destroy-selected',
                'show_name' => 'Can Destroy Selected Sites Additional Costs',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.importAdcosts',
                'show_name' => 'Can Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.importAdcostsPreview',
                'show_name' => 'Can View Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.storePreview',
                'show_name' => 'Can View store Preview',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.additional-costs.saveImport',
                'show_name' => 'Can Save Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Floor Routes
            [
                'name' => 'sites.floors.index',
                'show_name' => 'Can View Sites Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.create',
                'show_name' => 'Can Create Sites Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.store',
                'show_name' => 'Can Store Sites Floor',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.edit',
                'show_name' => 'Can Edit Sites Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.update',
                'show_name' => 'Can Update Sites Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.destroy-selected',
                'show_name' => 'Can Destroy Selected Sites Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.copyView',
                'show_name' => 'Can View Sites Copy Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.copyStore',
                'show_name' => 'Can Store Copy Sites Floor ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.pending.get',
                'show_name' => 'Can Get Pending floors ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.preview',
                'show_name' => 'Can  Preview floors ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.changes.save',
                'show_name' => 'Can Save Preview floors ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.importFloors',
                'show_name' => 'Can Import Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.importFloorsPreview',
                'show_name' => 'Can View Import Floors',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.storePreview',
                'show_name' => 'Can View store Preview',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.saveImport',
                'show_name' => 'Can Save Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //
            // Unit Routes
            [
                'name' => 'sites.floors.units.index',
                'show_name' => 'Can View Sites Floors Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.create',
                'show_name' => 'Can Create Site Floor Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.fab.create',
                'show_name' => 'Create Site Bifurcated Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.fab.store',
                'show_name' => 'Store Site Floor Bifurcated Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.store',
                'show_name' => 'Can Store Site Floor Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.edit',
                'show_name' => 'Can Edit Site Floor Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.update',
                'show_name' => 'Can Update Sites Floor Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.destroy-selected',
                'show_name' => 'Can Destroy Sites Floors Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.preview',
                'show_name' => 'Can Preview Unit ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.changes.save',
                'show_name' => 'Can  Save Preview Unit ',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.unitsImport.importUnits',
                'show_name' => 'Can Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.unitsImport.importUnitsPreview',
                'show_name' => 'Can View Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.unitsImport.storePreview',
                'show_name' => 'Can View store Preview',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.unitsImport.saveImport',
                'show_name' => 'Can Save Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Batchs Routes
            [
                'name' => 'batches.byid',
                'show_name' => 'Can Batches By id',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'batches.clear-all',
                'show_name' => 'Can clear batches',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sales Plan
            [
                'name' => 'sites.floors.units.sales-plans.index',
                'show_name' => 'Can View Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.create',
                'show_name' => 'Can Create Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.store',
                'show_name' => 'Can Store Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.edit',
                'show_name' => 'Can Edit Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.update',
                'show_name' => 'Can Update Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.destroy-selected',
                'show_name' => 'Can Destroy Selected Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.approve-sales-plan',
                'show_name' => 'Can Approve Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.units.sales-plans.disapprove-sales-plan',
                'show_name' => 'Can Disapprove Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //sales Plan Import
            [
                'name' => 'sites.floors.SalesPlanImport.importSalesPlan',
                'show_name' => 'Can Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.SalesPlanImport.importSalesPlanPreview',
                'show_name' => 'Can View Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.SalesPlanImport.storePreview',
                'show_name' => 'Can View store Preview',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.SalesPlanImport.saveImport',
                'show_name' => 'Can Save Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // sales Plan Additional Costs Import
            [
                'name' => 'sites.floors.spadcostsImport.importspadcosts',
                'show_name' => 'Can Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.spadcostsImport.importspadcostsPreview',
                'show_name' => 'Can View Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.spadcostsImport.storePreview',
                'show_name' => 'Can View store Preview',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.spadcostsImport.saveImport',
                'show_name' => 'Can Save Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // sales Plan Installments Import
            [
                'name' => 'sites.floors.spInstallmentsImport.ImportInstallments',
                'show_name' => 'Can Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.spInstallmentsImport.ImportPreviewinstallments',
                'show_name' => 'Can View Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.spInstallmentsImport.storePreviewInstallments',
                'show_name' => 'Can View store Preview',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.floors.spInstallmentsImport.saveImportInstallments',
                'show_name' => 'Can Save Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Sales Plan Print
            [
                'name' => 'sites.floors.units.sales-plans.templates.print',
                'show_name' => 'Can Print Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Stakeholders
            [
                'name' => 'sites.stakeholders.index',
                'show_name' => 'Can View Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.create',
                'show_name' => 'Can Create Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.store',
                'show_name' => 'Can Store Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.edit',
                'show_name' => 'Can Edit Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.update',
                'show_name' => 'Can Update Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.destroy',
                'show_name' => 'Can Destroy Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.destroy-selected',
                'show_name' => 'Can Destroy Selected Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.importStakeholders',
                'show_name' => 'Can Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.importStakeholdersPreview',
                'show_name' => 'Can View Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.storePreview',
                'show_name' => 'Can View store Preview',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.stakeholders.saveImport',
                'show_name' => 'Can Save Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Blacklisted Stakeholders
            // Stakeholders
            [
                'name' => 'sites.blacklisted-stakeholders.index',
                'show_name' => 'Can View Sites Blacklisted Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.blacklisted-stakeholders.create',
                'show_name' => 'Can Create Sites Blacklisted Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.blacklisted-stakeholders.store',
                'show_name' => 'Can Store Sites Blacklisted Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.blacklisted-stakeholders.edit',
                'show_name' => 'Can Edit Sites Blacklisted Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.blacklisted-stakeholders.update',
                'show_name' => 'Can Update Sites Blacklisted Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.blacklisted-stakeholders.destroy',
                'show_name' => 'Can Destroy Sites Blacklisted Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.blacklisted-stakeholders.destroy-selected',
                'show_name' => 'Can Destroy Selected Blacklisted Sites Stakeholders',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.blacklisted-stakeholders.importStakeholders',
                'show_name' => 'Can Import Blacklisted Stakeholder file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.blacklisted-stakeholders.importStakeholdersPreview',
                'show_name' => 'Can View Blacklisted Stakeholder Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.blacklisted-stakeholders.storePreview',
                'show_name' => 'Can View Blacklisted Stakeholder store Preview',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.blacklisted-stakeholders.saveImport',
                'show_name' => 'Can Save Blacklisted Stakeholder Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // Lead Sources Routes
            [
                'name' => 'sites.lead-sources.index',
                'show_name' => 'Can View Lead Sources',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.lead-sources.create',
                'show_name' => 'Can Create Lead Source',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.lead-sources.store',
                'show_name' => 'Can Store Lead Source',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.lead-sources.edit',
                'show_name' => 'Can Edit Lead Source',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.lead-sources.update',
                'show_name' => 'Can Update Lead Source',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.lead-sources.destroy-selected',
                'show_name' => 'Can Delete Selected Lead Sources',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // sales Plan Receipts
            [
                'name' => 'sites.receipts.index',
                'show_name' => 'Can View Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.create',
                'show_name' => 'Can Create Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.store',
                'show_name' => 'Can Store Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.show',
                'show_name' => 'Can View Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'name' => 'sites.receipts.edit',
            //     'show_name' => 'Can View Receipt Details',
            //     'guard_name' => 'web',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'sites.receipts.update',
            //     'show_name' => 'Can Update Receipts',
            //     'guard_name' => 'web',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'sites.receipts.destroy-selected',
            //     'show_name' => 'Can Destroy Selected Receipts',
            //     'guard_name' => 'web',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            [
                'name' => 'sites.receipts.make-active-selected',
                'show_name' => 'Can Make Active Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.destroy-draft',
                'show_name' => 'Can Destroy Draft Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.templates.print',
                'show_name' => 'Can Print Selected Receipts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'sites.receipts.importReceipts',
                'show_name' => 'Can Import Receipts File',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.importReceiptsPreview',
                'show_name' => 'Can View Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.storePreview',
                'show_name' => 'Can View store Preview of Import File',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.receipts.saveImport',
                'show_name' => 'Can Save Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Customer File Management Routes
            [
                'name' => 'sites.file-managements.customers',
                'show_name' => 'Can File Management Customers',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units',
                'show_name' => 'Can File Management Customers Units',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.index',
                'show_name' => 'Can Create Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.show',
                'show_name' => 'Can View Created Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.create',
                'show_name' => 'Can Create Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.store',
                'show_name' => 'Can Store Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.edit',
                'show_name' => 'Can Edit Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.update',
                'show_name' => 'Can Update Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.destroy-selected',
                'show_name' => 'Can Delete Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.customers.units.files.print',
                'show_name' => 'Can Print File',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // file management rebate incentive
            [
                'name' => 'sites.file-managements.rebate-incentive.index',
                'show_name' => 'Can View Rebate Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.rebate-incentive.create',
                'show_name' => 'Can Create Rebate Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.rebate-incentive.store',
                'show_name' => 'Can Store Rebate Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.rebate-incentive.edit',
                'show_name' => 'Can Edit Rebate Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.rebate-incentive.update',
                'show_name' => 'Can Update Rebate Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.view-files',
                'show_name' => 'Can View Customer Files',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // file management dealer incentive
            [
                'name' => 'sites.file-managements.dealer-incentive.index',
                'show_name' => 'Can View Dealer Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.dealer-incentive.create',
                'show_name' => 'Can Create Dealer Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.dealer-incentive.store',
                'show_name' => 'Can Store Dealer Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.dealer-incentive.approve',
                'show_name' => 'Can Approve Dealer Incentive',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File Refund
            [
                'name' => 'sites.file-managements.file-refund.index',
                'show_name' => 'Can View File Refund',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-refund.create',
                'show_name' => 'Can View File Refund',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-refund.store',
                'show_name' => 'Can View File Refund',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-refund.approve',
                'show_name' => 'Can Approve File Refund Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-refund.preview',
                'show_name' => 'Can Preview File Refund',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-refund.print',
                'show_name' => 'Can Print File Refund',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File Buy Back
            [
                'name' => 'sites.file-managements.file-buy-back.index',
                'show_name' => 'Can View File Buy Back',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-buy-back.create',
                'show_name' => 'Can View File Buy Back',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-buy-back.store',
                'show_name' => 'Can View File Buy Back',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-buy-back.approve',
                'show_name' => 'Can Approve File Buy Back Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-buy-back.preview',
                'show_name' => 'Can Preview File Buy Back',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-buy-back.print',
                'show_name' => 'Can Print File Buy Back',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File Cancellation
            [
                'name' => 'sites.file-managements.file-cancellation.index',
                'show_name' => 'Can View File Cancellation',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-cancellation.create',
                'show_name' => 'Can View File Cancellation',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-cancellation.store',
                'show_name' => 'Can View File Cancellation',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-cancellation.approve',
                'show_name' => 'Can Approve File Cancallation Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-cancellation.preview',
                'show_name' => 'Can Preview File Cancellation',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-cancellation.print',
                'show_name' => 'Can Print File Cancellation',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File resale
            [
                'name' => 'sites.file-managements.file-resale.index',
                'show_name' => 'Can View File Re-sale',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-resale.create',
                'show_name' => 'Can View File Re-sale',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-resale.store',
                'show_name' => 'Can View File Re-sale',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-resale.approve',
                'show_name' => 'Can Approve File Resale Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-resale.preview',
                'show_name' => 'Can Preview File Resale',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-resale.print',
                'show_name' => 'Can Print File Resale',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File title transfer
            [
                'name' => 'sites.file-managements.file-title-transfer.index',
                'show_name' => 'Can View File Title-Transfer',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-title-transfer.create',
                'show_name' => 'Can View File Title-Transfer',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-title-transfer.store',
                'show_name' => 'Can View File Title-Transfer',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-title-transfer.approve',
                'show_name' => 'Can Approve File Title Transfer Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-title-transfer.preview',
                'show_name' => 'Can Preview File Title Transfer',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-title-transfer.print',
                'show_name' => 'Can Print File Title Transfer',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File title adjustment
            [
                'name' => 'sites.file-managements.file-adjustment.index',
                'show_name' => 'Can View File Adjustment',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-adjustment.create',
                'show_name' => 'Can View File Adjustment',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-adjustment.store',
                'show_name' => 'Can View File Adjustment',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-adjustment.approve',
                'show_name' => 'Can Approve File Title Adjustment Request',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.file-adjustment.preview',
                'show_name' => 'Can Preview File Adjustment',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // File unit shifting
            [
                'name' => 'sites.file-managements.unit-shifting.index',
                'show_name' => 'Can View File Unit Shifting',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.unit-shifting.create',
                'show_name' => 'Can View File Unit Shifting',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.unit-shifting.store',
                'show_name' => 'Can View File Unit Shifting',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.file-managements.unit-shifting.preview',
                'show_name' => 'Can Preview File Unit Shifting',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Commands Route
            [
                'name' => 'commands.command',
                'show_name' => 'Can Commands Permissions',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Users
            [
                'name' => 'sites.users.index',
                'show_name' => 'Can View Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.create',
                'show_name' => 'Can Create Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.store',
                'show_name' => 'Can Store Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.edit',
                'show_name' => 'Can Edit Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.update',
                'show_name' => 'Can Update Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.destroy',
                'show_name' => 'Can Destroy Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.destroy-selected',
                'show_name' => 'Can Destroy Selected Sites Users',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.users.edit.password',
                'show_name' => 'Can Edit Sites Users Password',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // Users Teams
            [
                'name' => 'sites.teams.index',
                'show_name' => 'Can View Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.create',
                'show_name' => 'Can Create Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.store',
                'show_name' => 'Can Store Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.edit',
                'show_name' => 'Can Edit Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.update',
                'show_name' => 'Can Update Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.destroy',
                'show_name' => 'Can Destroy Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.teams.destroy-selected',
                'show_name' => 'Can Destroy Selected Sites Users Teams',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Custom Fields
            [
                'name' => 'sites.settings.custom-fields.index',
                'show_name' => 'Can View Custom Fields',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.custom-fields.create',
                'show_name' => 'Can Create Custom Fields',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.custom-fields.store',
                'show_name' => 'Can Store Custom Fields',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.custom-fields.edit',
                'show_name' => 'Can Edit Custom Fields',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.custom-fields.update',
                'show_name' => 'Can Update Custom Fields',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.custom-fields.destroy',
                'show_name' => 'Can Destroy Custom Fields',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.custom-fields.destroy-selected',
                'show_name' => 'Can Destroy Selected Custom Fields',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //Recovery Accounts
            [
                'name' => 'sites.accounts.recovery.dashboard',
                'show_name' => ' Can View Accounts Recovery Dashboard',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.accounts.recovery.calender',
                'show_name' => ' Can View Accounts Recovery Calender',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.accounts.recovery.salesPlan',
                'show_name' => ' Can View Accounts Recovery Sales Plan',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Chart Of Accounts
            [
                'name' => 'sites.accounts.charts-of-accounts.index',
                'show_name' => 'Can View Chart Of Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Accounts Ledger
            [
                'name' => 'sites.accounts.ledger.index',
                'show_name' => 'Can View Accounts Ledger',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Journal Entry
            [
                'name' => 'sites.accounts.journal-entry.index',
                'show_name' => 'Can View Journal Entries',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Accounts trial-balance
            [
                'name' => 'sites.accounts.trial-balance.index',
                'show_name' => 'Can View Accounts Trial Balance',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'sites.import.sample-download',
                'show_name' => 'Can Download sample File',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'sites.banks.importBanks',
                'show_name' => 'Can Import Banks Data',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.banks.importBanksPreview',
                'show_name' => 'Can View Imported file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.banks.storePreview',
                'show_name' => 'Can View store Preview',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.banks.saveImport',
                'show_name' => 'Can Save Import file',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Accounts First level
            [
                'name' => 'sites.settings.accounts.first-level.index',
                'show_name' => 'Can View First Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.first-level.create',
                'show_name' => 'Can Create First Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.first-level.store',
                'show_name' => 'Can Store First Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.first-level.edit',
                'show_name' => 'Can Edit First Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.first-level.update',
                'show_name' => 'Can Update First Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.first-level.destroy',
                'show_name' => 'Can Destroy First Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.first-level.destroy-selected',
                'show_name' => 'Can Destroy Selected First Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Accounts Second level
            [
                'name' => 'sites.settings.accounts.second-level.index',
                'show_name' => 'Can View Second Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.second-level.create',
                'show_name' => 'Can Create Second Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.second-level.store',
                'show_name' => 'Can Store Second Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.second-level.edit',
                'show_name' => 'Can Edit Second Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.second-level.update',
                'show_name' => 'Can Update Second Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.second-level.destroy',
                'show_name' => 'Can Destroy Second Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.second-level.destroy-selected',
                'show_name' => 'Can Destroy Selected Second Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Accounts Third level
            [
                'name' => 'sites.settings.accounts.third-level.index',
                'show_name' => 'Can View Third Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.third-level.create',
                'show_name' => 'Can Create Third Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.third-level.store',
                'show_name' => 'Can Store Third Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.third-level.edit',
                'show_name' => 'Can Edit Third Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.third-level.update',
                'show_name' => 'Can Update Third Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.third-level.destroy',
                'show_name' => 'Can Destroy Third Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.third-level.destroy-selected',
                'show_name' => 'Can Destroy Selected Third Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Accounts Fourth level
            [
                'name' => 'sites.settings.accounts.fourth-level.index',
                'show_name' => 'Can View Fourth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fourth-level.create',
                'show_name' => 'Can Create Fourth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fourth-level.store',
                'show_name' => 'Can Store Fourth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fourth-level.edit',
                'show_name' => 'Can Edit Fourth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fourth-level.update',
                'show_name' => 'Can Update Fourth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fourth-level.destroy',
                'show_name' => 'Can Destroy Fourth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fourth-level.destroy-selected',
                'show_name' => 'Can Destroy Selected Fourth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Accounts Fifth level
            [
                'name' => 'sites.settings.accounts.fifth-level.index',
                'show_name' => 'Can View Fifth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fifth-level.create',
                'show_name' => 'Can Create Fifth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fifth-level.store',
                'show_name' => 'Can Store Fifth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fifth-level.edit',
                'show_name' => 'Can Edit Fifth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fifth-level.update',
                'show_name' => 'Can Update Fifth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fifth-level.destroy',
                'show_name' => 'Can Destroy Fifth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.accounts.fifth-level.destroy-selected',
                'show_name' => 'Can Destroy Selected Fifth Level Accounts',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // import images
            [
                'name' => 'sites.settings.import',
                'show_name' => 'Can View Images Import',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.import.images.index',
                'show_name' => 'Can View Images Import',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.import.images.store',
                'show_name' => 'Can Save Images Import',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.import.images.create',
                'show_name' => 'Can Images Import',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sites.settings.import.images.cancel',
                'show_name' => 'Cancel Images Import',
                'guard_name' => 'web',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        (new Role())->find(1)->givePermissionTo((new Permission())->pluck('id'));
    }
}
