<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Models\SalesPlanInstallments;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SalesPlanInstallmentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        (new SalesPlanInstallments())->insert([
            [
                'sales_plan_id' => 1,
                'date' => Carbon::parse('2022-12-18'),
                'amount' => 3399500,
                'type' => 'downpayment',
                'paid_amount' => 3399500,
                'remaining_amount' => 0,
                'details' => 'Downpayment',
                'remarks' => 'Paid',
                'installment_order' => 0,
                'status' => 'paid',
                'last_paid_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sales_plan_id' => 1,
                'date' => Carbon::parse('2022-12-18'),
                'amount' => 1019850,
                'type' => 'installment',
                'paid_amount' => 1019850,
                'remaining_amount' => 0,
                'details' => '1st Installment',
                'remarks' => 'Paid',
                'installment_order' => 1,
                'status' => 'paid',
                'last_paid_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sales_plan_id' => 1,
                'date' => Carbon::parse('2023-03-18'),
                'amount' => 1019850,
                'type' => 'installment',
                'paid_amount' => 1019850,
                'remaining_amount' => 0,
                'details' => '2nd Installment',
                'remarks' => 'Paid',
                'installment_order' => 2,
                'status' => 'paid',
                'last_paid_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sales_plan_id' => 1,
                'date' => Carbon::parse('2023-06-16'),
                'amount' => 1019850,
                'type' => 'installment',
                'paid_amount' => 1019850,
                'remaining_amount' => 0,
                'details' => '3rd Installment',
                'remarks' => 'Paid',
                'installment_order' => 3,
                'status' => 'paid',
                'last_paid_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sales_plan_id' => 1,
                'date' => Carbon::parse('2023-09-14'),
                'amount' => 1019850,
                'type' => 'installment',
                'paid_amount' => 509925,
                'remaining_amount' => 509925,
                'details' => '4th Installment',
                'remarks' => 'Partially Paid',
                'installment_order' => 4,
                'status' => 'partially_paid',
                'last_paid_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sales_plan_id' => 1,
                'date' => Carbon::parse('2023-12-13'),
                'amount' => 1019850,
                'type' => 'installment',
                'paid_amount' => 0,
                'remaining_amount' => 1019850,
                'details' => '5th Installment',
                'remarks' => 'UnPaid',
                'installment_order' => 5,
                'status' => 'unpaid',
                'last_paid_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sales_plan_id' => 1,
                'date' => Carbon::parse('2024-03-12'),
                'amount' => 1019850,
                'type' => 'installment',
                'paid_amount' => 0,
                'remaining_amount' => 1019850,
                'details' => '6th Installment',
                'remarks' => 'Unpaid',
                'installment_order' => 6,
                'status' => 'unpaid',
                'last_paid_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sales_plan_id' => 1,
                'date' => Carbon::parse('2024-06-10'),
                'amount' => 1019850,
                'type' => 'installment',
                'paid_amount' => 0,
                'remaining_amount' => 1019850,
                'details' => '7th Installment',
                'remarks' => 'Unpaid',
                'installment_order' => 7,
                'status' => 'unpaid',
                'last_paid_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sales_plan_id' => 1,
                'date' => Carbon::parse('2024-09-08'),
                'amount' => 1019850,
                'type' => 'installment',
                'paid_amount' => 0,
                'remaining_amount' => 1019850,
                'details' => '8th Installment',
                'remarks' => 'Unpaid',
                'installment_order' => 8,
                'status' => 'unpaid',
                'last_paid_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sales_plan_id' => 1,
                'date' => Carbon::parse('2024-12-07'),
                'amount' => 1019850,
                'type' => 'installment',
                'paid_amount' => 0,
                'remaining_amount' => 1019850,
                'details' => '9th Installment',
                'remarks' => 'Unpaid',
                'installment_order' => 9,
                'status' => 'unpaid',
                'last_paid_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sales_plan_id' => 1,
                'date' => Carbon::parse('2025-03-07'),
                'amount' => 1019850,
                'type' => 'installment',
                'paid_amount' => 0,
                'remaining_amount' => 1019850,
                'details' => '10th Installment',
                'remarks' => 'Unpaid',
                'installment_order' => 10,
                'status' => 'unpaid',
                'last_paid_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
